name: 'Rancher Login Action'
description: 'Login into Rancher instance and select project to work with'
inputs:
  context:
    description: 'Rancher context (numeric project identifier)'
    required: true
  token:
    description: 'Rancher API token'
    required: true
  url:
    description: 'Rancher server URL'
    required: true

runs:
  using: "composite"
  steps:
    - run: curl -LO -sS https://github.com/rancher/cli/releases/download/v2.6.7/rancher-linux-amd64-v2.6.7.tar.gz
      shell: bash
    - run: tar -xf rancher-linux-amd64-v2.6.7.tar.gz
      shell: bash
    - run: mv rancher-v2.6.7/rancher /usr/local/bin/rancher
      shell: bash
    - run: curl -LO -sS https://dl.k8s.io/release/v1.25.0/bin/linux/amd64/kubectl
      shell: bash
    - run: mv kubectl /usr/local/bin/kubectl
      shell: bash
    - run: chmod +x /usr/local/bin/kubectl
      shell: bash
    - run: rancher login ${{ inputs.url }} --token ${{ inputs.token }} --context ${{ inputs.context }}
      shell: bash
