on: [push]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          token: ${{ secrets.RANCHER_TOKEN }}
          url: ${{ secrets.RANCHER_URL }}
          context: ${{ secrets.RANCHER_CONTEXT }}
      - run: rancher ps
