on: [push]

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test login
        uses: ./
      - run: rancher --version
      - run: kubectl --version
